GFDRR/thinkhazard

- setup.py
As discussed we'll use jinja2 as the template engine/language. This commit removes the pyramid_mako dependency and adds the pyramid_jinja2 dependency. The pyramid_chameleon dependency will be removed in the future. It's not removed for now as the default page relies on it.
> Use jinja2 and pyramid_jinja2

- Makefile
- README.rst
- development.ini
- production.ini
- setup.py
- thinkhazard/__init__.py
- thinkhazard/models.py
- thinkhazard/scripts/initializedb.py
- thinkhazard/static/js/index.js
- thinkhazard/templates/index.jinja2
- thinkhazard/views.py
This PR adds a JSON web service for searching admin units, and make the search field rely on that search service.
The URL of the service is `/adminunit` and the `q` parameter is used for searching admin units. For example: `/adminunit?q=mor`.
> Add admin unit search web service

- Makefile
- dev-requirements.txt
- requirements.txt
- setup.py
- thinkhazard/__init__.py
With this PR we use Pyramid's cache buster for the application's static resources. This is to avoid problems because of the Varnish cache we use on AWS.
This requires using the development version of Pyramid (1.6.dev0), which we download from GitHub.
> Add Pyramid's cache buster

- thinkhazard/__init__.py
- thinkhazard/static/js/search.js
- thinkhazard/templates/base.jinja2
- thinkhazard/views.py
This is as suggested by @pgiraud. Let's use the same terms everywhere to avoid any confusion.
> Change admindiv to administrativedivision in the code

- thinkhazard/static/js/search.js
Changed order of administrative levels and make the higher level more obvious in the search results so that it's more intuitive for the user.
See screenshots.
Before:
After:
> Using a custom template for typeahead, makes search results more readable

- data/thinkhazard.xml
- thinkhazard/views/map.py
With this PR the division boundaries are drawn on the map even when there's no hazard type selected. This PR also increases the map font size.
Fixes https://github.com/GFDRR/thinkhazard/issues/43 https://github.com/GFDRR/thinkhazard/issues/38.
> Show subdivisions in map when no hazard type is selected

- thinkhazard/models.py
- thinkhazard/views/map.py
This commit changes the SRID of the admin division geometry column from 4326 to 3857. It also renames the column from geometry_wgs84 to geom.
> Change admin division geometry to 3857

- thinkhazard/views/report.py
Rely on the enum_categorytype:order column for the ordering of the hazard type icons and the elements of the overview list.
Fixes https://github.com/GFDRR/thinkhazard/issues/58.
> Use the enum_categorytype:order column

- thinkhazard/static/js/report.js
`event.offsetX` and `event.offsetY` are `undefined` on FF. This was fixed in FF very recently, but it's not available in the Firefox versions most people currently use.
Fixes https://github.com/GFDRR/thinkhazard/issues/64.
> Fix map interactivity issue on FF

- package.json
- thinkhazard/static/less/report.less
- thinkhazard/templates/report.jinja2
This PR removes OpenLayers 3 entirely. For now. We may revisit this choice in the future.
> Remove OpenLayers 3

- thinkhazard/models.py
- thinkhazard/templates/report.jinja2
- thinkhazard/views/report.py
This adds the additional information to report pages. Please review.
Fixes https://github.com/GFDRR/thinkhazard/issues/66.
> Add Additional Information to the report pages

- thinkhazard/static/js/report.js
- thinkhazard/static/less/report-layout.less
- thinkhazard/templates/report.jinja2
This changes the division name text to a link in the report page. And when that link is clicked we go back to the "overview" content.
Please review.
Fixes https://github.com/GFDRR/thinkhazard/issues/60.
> Go back to overview page when division link is clicked

- thinkhazard/static/js/report.js
- thinkhazard/templates/report.jinja2
Allows to keep hazard when drilling up/down to other division
Fixes https://github.com/GFDRR/thinkhazard/issues/79.
> Add hash in url for selected hazard type

- thinkhazard/models.py
This PR renames the `recommendationorder` and `additionalinformationorder` colunms to `order`. This is to match the schema used by BRGM and fix the data import issue we currently face.
> Rename order columns to "order"

- thinkhazard/views/map.py
A buffer is now added around the extent of the admin division. The size of the buffer is 1/8th the size of the admin division extent.
Fixes https://github.com/GFDRR/thinkhazard/issues/87.
> Use a buffer for the map

- thinkhazard/models.py
This is to reflect a correction by the BRGM team on the schema.
> Add returnperiod_id column to metadata table

- thinkhazard/templates/report.jinja2
This was probaby missing from https://github.com/GFDRR/thinkhazard/issues/44
> report page: no-data hazards are now unselectable

- Makefile
- apache.conf
With this PR one can use `make modwsgi INSTANCEID=myuserid` to generate an Apache mod_wsgi config declaring a WSGI application at `/myuserid/wsgi`. By default `INSTANCEID` is `main`, meaning that the demo instance will be available at `/main/wsgi` (instead of `/thinkhazard/wsgi` as today).
> Make it possible to create user instances

- setup.py
simplejson is necessary when using Papyrus' GeoJSON renderer.
> Add simplejson as a dependency

- Makefile
This PR makes `make clean` remove `.timestamp` files. It removes the `.timestamp` files that can be quickly rebuilt. For example, it won't remove `mode_modules.timestamp`, because re-installing all the node dependencies takes a long time. `make cleanall` is the target to use to remove all the build artifacts.
> Make make clean remove timestamp files

- Makefile
This renames the `watchless` target to `watch`, and makes it watch the entire `thinkhazard/static` dir instead of just the `thinkhazard/static/less` dir. It also runs `make build` instead of just rebuilding the CSS files.
> Rename watchless to watch

- thinkhazard/static/less/common.less
- thinkhazard/templates/report.jinja2
With this pull request I have fix bad alignment of hazard type and level.
I also have fixed styling when displayed in overview.
Please review.
> Hazard type (alignment + overview)

- thinkhazard/static/less/report.less
- thinkhazard/templates/report.jinja2
Is it OK to use "top: 0.5em" (in report.less)?
Please review.
> Add logo to footer and let it use all width

- Makefile
There were font-awesome related things left in the Makefile. This PR removes them.
> Remove font-awesome related rules from Makefile

- Makefile
This pull request fixes issues with application not working in wsgi mode.
Using a first virtualenv to install a new one helps.
Also the way to get the path to python site-packages for the wsgi script needed an update since distutils doesn't seem to work well.
> Use a more recent version of virtualvenv

- thinkhazard/static/less/common.less
- thinkhazard/static/less/report.less
- thinkhazard/static/less/variables.less
- thinkhazard/templates/report.jinja2
Fix #319, tested in FF & Chrome.
> Add a hazard level arrow in report

- thinkhazard/static/js/search.js
Fixes #358.
See https://github.com/twitter/typeahead.js/issues/1232 and https://github.com/twitter/typeahead.js/issues/1218
> Workaround for typeahead issue not showing all results

- thinkhazard/templates/report.jinja2
- thinkhazard/tests/__init__.py
- thinkhazard/views/report.py
This is a proposal for https://github.com/GFDRR/thinkhazard/issues/40
Here's a screenshot taken during tests:
(in which the hazardset is named "test")
Also, tests had to be updated as a result of https://github.com/GFDRR/thinkhazard_common/pull/9
> The decisiontree-selected hazardset source is displayed under the map

- thinkhazard/templates/faq.jinja2
Added several new FAQs, edited some existing (including removing space in Think Hazard!, and adding links to 'contact us' page - these are placeholders taking user to FAQ page). TO BE UPDATED when Contact Us page is active.
> Update faq.jinja2: add/edit FAQs

- thinkhazard_processing.yaml
@stufraser1 said:
```
Francois, can you confirm whether the thresholds for global data (cm/s^2) been updated in ThinkHazard! to 200 for High, and 100 for Med/Low (not 2 and 1, as currently included)?
```
For now, the EQ thresholds in the tool are the same for global and local data.
> EQ thresholds differ for high/med/low

- thinkhazard/processing/__init__.py
When loading settings for the processing scripts
Without this code change, the pyramid application is failing in modwsgi. It fails by trying to open "/var/www/development.ini" which doesn't exist.
The app settings may need some rework now that we only have one repository.
See https://github.com/GFDRR/thinkhazard/blob/master/thinkhazard/scripts/import.py#L66 for an example.
> Prevent pyramid from failing in modwsgi

- thinkhazard/models.py
- thinkhazard/processing/harvesting.py
This resets the `downloaded`, `complete` and `processed` statuses when needed as metadata changes.
> Handle metadata changes in harvesting

- thinkhazard/processing/harvesting.py
dry-run is handled by enclosing transaction.
> Remove dry-run test in further resources harvesting

- thinkhazard/__init__.py
- thinkhazard/models.py
- thinkhazard/static/less/bootstrap.less
- thinkhazard/templates/admin/admindiv_hazardsets.jinja2
- thinkhazard/templates/admin/hazardsets.jinja2
- thinkhazard/views/admin.py
With this pull request we can see the list of administrative divisions and the corresponding hazard set that was chosen (via decision tree) for a given hazard type.
Example : http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/pierre/wsgi/hazardsets/FL
Fixes #419.
> Show hazarset by admin div level 2 list

- thinkhazard/processing/processing.py
Now we get this for exemple:
```
INFO - EQ-GLOBAL-GAR15
INFO -   Cleaning previous outputs
INFO -   Opening raster files
INFO -   Iterating over 926 administrative divisions
INFO -   Closing raster files
ERROR - Traceback (most recent call last):
File "/srv/home/amorvan/thinkhazard/thinkhazard/processing/processing.py", line 75, in process
process_hazardset(id[0], force=force)
File "/srv/home/amorvan/thinkhazard/thinkhazard/processing/processing.py", line 147, in process_hazardset
outputs = create_outputs(hazardset, layers, readers)
File "/srv/home/amorvan/thinkhazard/thinkhazard/processing/processing.py", line 219, in create_outputs
readers, shape)
File "/srv/home/amorvan/thinkhazard/thinkhazard/processing/processing.py", line 314, in notpreprocessed_hazardlevel
layer.hazardunit)) …
```
> Fix ProcessException so that message appears in stack trace. Fix #402

- Makefile
- README.rst
- apache.conf
Note that with this method, authentification is needed only with WSGI, not for tests.
> Add basic authentification for admin ui

- thinkhazard/views/admin.py
When a user edits either a technical or climate change recommendation, the page reloads after form submit. Then the user is tempted to use the back button on his browser to get back to the list of recommendations. It may result (in Firefox for example) to showing a list which is not up-to-date, and thus confusion about whether the change has been taken into account or not.
This pull request fixes this behavior by redirecting the user directly to the list after form submit.
> Redirect to technical recommendations after form submit

- data/geonode_regions_to_administrative_divisions_code.csv
Still missing 4 regions: Channel islands, Aland islands, Saint-Barthelemey and Saint Martin.
> Added geonode regions of the world to the csv. This fixes #441

- data/geonode_regions_to_administrative_divisions_code.csv
This PR builds upon https://github.com/GFDRR/thinkhazard/pull/447 but still misses the associations for GeoNode continents:
```
"Africa",10
"Americas",254
"Antarctica",16
"Asia",6
"Europe",5
"Middle East",15
"Pacific",256
```
> More GeoNode Regions to GAUL relations

- thinkhazard/models.py
- thinkhazard/views/admin.py
This PR supersedes #470.
When using a join_depth set to 2, which is better, the "administrative divisions hazardsets" in the admin UI doesn't do the job in a performant way.
With the current pull request, I fix the join_depth value, and change the query for admin page to work with the new value.
Please review.
> Change query to make it work with join_depth 2

- thinkhazard/__init__.py
With scheduler created at import time, we have errors in processing scripts whereas is not used there.
> Do not create apscheduler at import time

- thinkhazard/tests/views/test_report.py
- thinkhazard/views/pdf.py
> Don't fail with accentuated division name when getting PDF report

- thinkhazard/models.py
- thinkhazard/processing/completing.py
- thinkhazard/processing/harvesting.py
- thinkhazard/processing/processing.py
- thinkhazard/scripts/import.py
- thinkhazard/templates/admin/hazardsets.jinja2
With this pull request the processed column is not a boolean anymore but a date instead.
If the value is None, it means that the hazard set is not processed.
> Store processed as date

- thinkhazard/templates/faq.jinja2
New FAQ directs users to a sheet that shows the comparison of hazard level given in ThinkHazard! and the comparison with expert expectations.
It also corrects the direction for users to give feedback via the feedback button, rather than the FAQ page
> Updated to add a new FAQ

- thinkhazard/tests/views/test_report.py
- thinkhazard/views/pdf.py
Prevents filesystem overload
Fixes #534.
@arnaud-morvan Can you please review?
> Store PDFs in YYYY/MM subdirectories

- thinkhazard_processing.yaml
We're using 9999 as fake value instead of 5 because hazard set can have a 5 years return period though it shouldn't be taken into account.
> Use a fake value for mask return period

- thinkhazard_processing.yaml
This way datasets for West Africa countries are taken into account.
> Take 1000 return period into account for EQ LOW

- alembic.ini
- alembic/env.py
With this pull request I address the following issue.
When instances are not specific, integrator usually don't set the database url in `local.ini` since the default values are already correct and don't need to be overwritten.
In this case, the `alembic.ini` was taken into account. This raised two problems:
- race condition of config reading made so the admin database was taken into account for both admin and public applications,
- the urls in `alembic.ini` were not correctly set.
> alembic fix

- .gitignore
- Makefile
- development.ini
- production.ini
- thinkhazard/__init__.py
- thinkhazard/filters.py
- thinkhazard/settings.py
- thinkhazard/templates/about_body.jinja2
Instead of executing "git describe" each time the page is displayed (which doesn't work correctly in apache mod_wsgi), we put the revision number in an ".ini" and load it via the settings.
> Get git version (new strategy)

- apache.conf
Fixes process groups overlap issue.
With the previous apache configuration we were having issues with the public database being used by the admin application. Thus the administrative UI were displaying information not relative to the correct database.
Procedure to reproduce:
- restart apache,
- load public interface in browser,
- load admin interface in browser,
- reload admin interface several times and compare results.
We discovered that it was due to the fact that the WSGI application were actually sharing the same processes (same pid). The error was apparently showing up randomly but in fact the number of processed (4) was taken into account.
The [mod_wsgi debugging techniques](http://modwsgi.readthedocs.org/en/develop/user-guides/debugging-techniques.html) helped me a lot and I …
> Change order of apache config directives

- thinkhazard/processing/completing.py
Fix #618.
To update an existing database, execute : 
```
UPDATE processing.hazardset SET complete = FALSE
```
and ``make complete``.
This will update quality fields in hazardset table.
> Do not use mask layer for hazardset quality calculation

- thinkhazard/scripts/publish.py
Happens on recent Debian boxes:
```
sudo -u postgres /etc/init.d/postgresql restart
Restarting postgresql (via systemctl): postgresql.serviceFailed to get D-Bus connection: No such file or directory
failed!
```
> Fix errors when restarting postgreSQL

- thinkhazard/views/report.py
Since the download link may be outside the geonode
Fixes #517
> Link to geonode document page instead of download link

- thinkhazard/__init__.py
- thinkhazard/static/js/report.js
- thinkhazard/static/less/report.less
- thinkhazard/templates/report.jinja2
- thinkhazard/views/report.py
Fixes #678.
With this pull request the World Bank mapbox tileset is used.
Also a new interaction is added to the map. It allows users to navigate to neighbouring divisions. This helps going to display and navigate to disputed areas.
> Change background layer and show neighbouring divisions

- package.json
- thinkhazard/static/js/report.js
- thinkhazard/views/report.py
Fixes #655.
Interactivity enhanced by making the really small and scattered islands a bit bigger than they actually are.
Demo
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/small_islands/en/report/154-maldives/CY
http://wb-thinkhazard.dev.sig.cloud.camptocamp.net/small_islands/en/report/189-palau/CY
@stufraser1 Can you please validate this?
> Make the polygons bigger if they are really small

- thinkhazard/processing/harvesting.py
This commit allow hazard type list separated by comma with or without
space around comma.
> Fix parsing of hazard types in "supplemental information" field

- thinkhazard/processing/harvesting.py
Previously, TH used to harvest `distribution_url` which was a fully qualified URL, but now that we're harvesting `detail_url`, which is a relative URL, we need to patch the code to take into account geonode base URL.
> Add geonode base URL as prefix for detail_url

- alembic/versions/7f0c2b165740_add_column_hazardset_processing_error.py
- requirements.txt
- thinkhazard/models.py
- thinkhazard/processing/__init__.py
- thinkhazard/processing/completing.py
- thinkhazard/processing/downloading.py
- thinkhazard/processing/harvesting.py
- thinkhazard/processing/processing.py
- thinkhazard/templates/admin/hazardsets.jinja2
- thinkhazard/tests/processing/test_completing.py
> [processing] Fix errors and improve error handling 

- thinkhazard/processing/harvesting.py
- thinkhazard/tests/processing/test_harvesting.py
Avoid corrupting data in case of error 500 from geonode
> Handle HTTP status codes in harvester

- thinkhazard/processing/processing.py
=> Red cross and "No output generated" will appear in /admin/hazardsets.
> Consider no output as a processing error

- thinkhazard/processing/harvesting.py
Because new file may have the same name as old one.
> Delete layer from cache if data_lastupdated_date has changed

- Dockerfile
- docker/testdb/Dockerfile
- tests/processing/__init__.py
- tests/processing/test_harvesting.py
- tests/views/test_report.py
- thinkhazard/models.py
- thinkhazard/processing/harvesting.py
PR deletes layers, hazardsets and corresponding output in DB that were not harvested from geonode (without using force), to prevent conflicts between thinkhazard application and geonode data
Notes:
* does not handle changing hazardset ids (eg. SSBN => FATHOM) => should not happen, but can be resolved using `harvest --force`
> Deletes non-harvested layers and hazardsets

- thinkhazard/templates/report_hazard_category.jinja2
Displays None under data source map if no layer of hazardset has return period to prevent shift of data owner and intensity unit info into wrong lines.
> [GSWBTH-20] Displays None if no layer has return period

- thinkhazard/static/js/report.js
PR requests source and legend of first available layer if no layer for requested hazardlevel is available which usually happens for hazardlevel VLO / hazardlevel_id 4
> [GSWBTH-15] Displays source and legend also if no layer for requested hazardlevel available

- thinkhazard/views/report.py
PR prevents neighbours.geojson request from failing if a geometry is null and returns null geometry in response instead (Monaco in case of France's neighbor)
Note: Adapted report_geojson(request) the same way for consistency
> [GSWBTH-46] Returns neighbours geojson also if geom null

- thinkhazard/processing/harvesting.py
... but keeps logic to not harvest prepocessed layers with hazard_period which ensures to prevent harvesting multiple preprocessed layers for same hazardset
> [GSWBTH-47] Harvests hazard_unit for preprocessed layers

- thinkhazard/processing/downloading.py
In Openshift container, download status in database is not reliable.
> Always download in force mode

- alembic/versions/33fe28fefaff_add_simplified_geom.py
- thinkhazard/models.py
- thinkhazard/processing/import.py
- thinkhazard/scripts/simplify.sql
- thinkhazard/views/pdf.py
- thinkhazard/views/report.py
PDF rendering on United States takes approximatively 15 seconds while it was failing after 2 minutes before.
Simultaneous rendering sometimes prevent Gunicorn from restarting. But this seems to be an development only issue as it appends when Gunicorn auto-reload when ovewriting python files in docker volume.
Simplified geometries seems a little more accurate than before but rendered really faster.
Neighbours rendering on US take 1s now instead of 15s before.
Note: It also fix the artefact on Russia geometry when displaying United States.
=> No, I was working with old divisions, error with Russia seems related to new dataset.
> Speedup PDF rendering

- thinkhazard/static/js/report.js
It seems that at some time there was two superposed styles (one from "stufraser1" and one from "gsdpm").
The one from "gsdpm" does not work anymore so I do not know how it should looks like.
The new one from "camptocamp" looks very similar to "stufraser1", a little more rivers and city labels appear at the same scale.
> Replace Mapbox style by camptocamp one
