.gitignore
MANIFEST.in
Makefile
development.ini
package.json
production.ini
setup.py
thinkhazard/__init__.py
thinkhazard/static/js/index.js
thinkhazard/static/less/thinkhazard.less
thinkhazard/templates/index.jinja2
thinkhazard/views.py

This PR sets up the infrastructure for client-side development. It also creates a simple Bootstrap-based index page with a typeahead-based search field.
Please review.

Set up infrastructure for client development

---

thinkhazard/subscribers.py
thinkhazard/views.py

As they will be used in every page of the application.

Make debug and node_modules renderer globals

---

doc/database.md

Add a document explaining how to create and populate the database.

Add a database doc

---

doc/database.md

Update the database.md doc for the insertion of the Morroco/flood data recently provided by BRGM.

Update the database doc

---

Makefile
README.rst
data/thinkhazard.xml
development.ini
production.ini
setup.py
thinkhazard/__init__.py
thinkhazard/models.py
thinkhazard/static/js/report.js
thinkhazard/static/js/search.js
thinkhazard/static/less/common.less
thinkhazard/static/less/report-layout.less
thinkhazard/templates/base.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/views/index.py
thinkhazard/views/map.py
thinkhazard/views/report.py
thinkhazard/views/search.py

This PR adds a map to the report page. The map has two layers: a [NaturalEarth](http://www.naturalearthdata.com/) layer as the background layer and an "hazard" layer based on the administrative division and hazard data.
The map is created with Mapnik. UTFGrid is used to provide an "interactive" map, with the mouse cursor changing when over a subdivision. Subdivisions can be clicked to load a new hazard report.
Note that the "hazard" layer doesn't yet have the correct colors (based on the hazard category of each division). This PR just focuses on adding a map to the report page. And I'd like to address the rest with separate PRs.
Please review. In the mean time I'm going to test the branch on the demo server.

Create map and UTFGrid using Mapnik

---

data/thinkhazard.xml
thinkhazard/models.py
thinkhazard/static/js/report.js
thinkhazard/static/less/common-variables.less
thinkhazard/static/less/report-layout.less
thinkhazard/templates/report.jinja2
thinkhazard/views/map.py
thinkhazard/views/report.py

With this PR we draw a classified map instead when an hazard type has been selected by the user.

Display a classified map

---

thinkhazard/models.py
thinkhazard/templates/report.jinja2
thinkhazard/views/report.py

This PR connects the report view to the database. The hazard types, category types and recommendations are now read from the database.
With @fvanderbiest and @pgiraud away this week I'm going to merge this and update the demo server.

Connect report view to database

---

thinkhazard/views/map.py

The subdivisions are displayed for admin levels 0 and 1, while the division itself is displayed for admin level 0.

Display entire division for admin level 2

---

thinkhazard/templates/report.jinja2
thinkhazard/views/report.py

Display hazard category description

---

thinkhazard/templates/report.jinja2

Remove recommendation title in UI

---

thinkhazard/models.py
thinkhazard/templates/report.jinja2
thinkhazard/views/report.py

Recommendations are ordered based on the rel_hazardcatetgory_recommendation recommendationorder column.
Fixes https://github.com/GFDRR/thinkhazard/issues/47.

Order recommendations in the page

---

data/thinkhazard.xml
thinkhazard/views/map.py

This fixes two issues with the "overview" map:
* The mouse cursor changes only when hovering labels
* The map does not include more than 4 sub-divisions

Fix map-related issues

---

thinkhazard/static/less/bootstrap.less
thinkhazard/static/less/common.less

The goal of this pull request is to get a smaller css file by removing any dependence on openlayers and by loading only the classes we use from bootstrap.

LESS optimizations

---

thinkhazard/static/less/index-layout.less
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2

Pgiraud links

---

thinkhazard/static/js/report.js
thinkhazard/static/js/search.js

This PR makes some refactoring to the JavaScript code.

JavaScript code refactoring

---

thinkhazard/static/less/report-layout.less

Fade the legend colors out (opacity)

---

thinkhazard/static/js/report.js

Show overview when hash is empty

---

thinkhazard/static/less/report-layout.less

Prevent scroll when tab changes

---

thinkhazard/static/less/report.less

Fix color for hazard links

---

data/thinkhazard.xml
thinkhazard/models.py
thinkhazard/views/report.py

Fixes https://github.com/GFDRR/thinkhazard/issues/105.

Eliminate hazard report inconsistencies

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Remove some unrequired nesting in HTML

---

thinkhazard/models.py
thinkhazard/static/js/report.js
thinkhazard/views/report.py

This PR adds an `hazardLevel` property to the GeoJSON features returned by the `report_json` service.
I also took the opportunity to reduce the number of objects created by the OpenLayers style functions.
Please review.

Add hazardLevel property to GeoJSON features

---

thinkhazard/static/js/report.js

This PR uses different colors based on the hazard levels for the admin divisions on the map. I also refactored the js code a bit.
Please review.

Add map choropleths

---

package.json
thinkhazard/static/js/search.js
thinkhazard/static/less/common.less
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/templates/search.jinja2

Enter key press support for typeahead

---

thinkhazard/templates/base.jinja2
thinkhazard/templates/report.jinja2

Fixes #89 
Can still be modified later.

Better title for report page

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2
thinkhazard/views/report.py

We're still missing real icons, but this can be modified later.
Please review.

Layout and style for hazard type icons

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

GFDRR logo with hover effect

---

thinkhazard/static/less/common.less
thinkhazard/static/less/report.less

Font family needs to be set only once

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Recommendations list styling

---

thinkhazard/static/less/common.less
thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

ThinkHazard logo and search input

---

thinkhazard/static/less/common.less

header background

---

thinkhazard/templates/report.jinja2

Open links for additional information in new tab/window

---

thinkhazard/templates/report.jinja2

Overview button not shown for overview

---

README.rst
thinkhazard/__init__.py

This PR makes setting `local_settings_path` in the ini file optional. It also adds instructions for updating the demo instance in the `README.rst` file.

Changes for main deployment

---

thinkhazard/static/less/bootstrap.less
thinkhazard/static/less/common.less
thinkhazard/static/less/report.less
thinkhazard/templates/base.jinja2
thinkhazard/templates/index.jinja2
thinkhazard/templates/navbar.jinja2
thinkhazard/templates/report.jinja2

Add nav. bar links and add style

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Add style to hazard type and header

---

thinkhazard/static/less/common.less
thinkhazard/static/less/report.less

Fix css shapes antialiasing in firefox

---

thinkhazard/static/js/report.js
thinkhazard/templates/base.jinja2
thinkhazard/views/report.py

Adding support for drill-down on map

---

thinkhazard/templates/report.jinja2

Fix map caption

---

thinkhazard/static/js/report.js
thinkhazard/templates/report.jinja2

Fixes #197.
#198 should be merged first.

Pgiraud avoid drill down

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Fixes https://github.com/GFDRR/thinkhazard/issues/144
Please review.

Showing a tooltip when hovering a admin division

---

thinkhazard/static/less/bootstrap.less
thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Adding zoomin help box

---

thinkhazard/templates/report.jinja2

move overview button to the left

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Better layout for the legend

---

thinkhazard/static/js/search.js
thinkhazard/static/less/common.less
thinkhazard/static/less/index.less
thinkhazard/static/less/report.less
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/templates/search.jinja2

Replace IDs in HTML elements with css class

---

thinkhazard/static/less/report.less

factorize the level of mixin

---

thinkhazard/static/less/common.less
thinkhazard/static/less/index.less
thinkhazard/static/less/report.less
thinkhazard/templates/index.jinja2
thinkhazard/views/index.py

Hazard icons are now using webfont in home page as well

---

thinkhazard/static/less/index.less
thinkhazard/templates/index.jinja2

Change baseline on front page

---

thinkhazard/static/less/common.less
thinkhazard/static/less/index.less
thinkhazard/static/less/report.less
thinkhazard/templates/common.jinja2
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2

change color and syle of the thinkhazard logo

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Change hazard selection coloring

---

thinkhazard/static/less/common.less
thinkhazard/templates/report.jinja2

style hazard name

---

thinkhazard/static/less/common.less
thinkhazard/static/less/index.less
thinkhazard/templates/base.jinja2

Front page search and autocompletion

---

thinkhazard/static/less/index.less
thinkhazard/templates/common.jinja2
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2

Pgiraud front page logo

---

thinkhazard/static/less/common.less
thinkhazard/static/less/report.less

style hazard level

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

generalize hazard level label

---

thinkhazard/static/less/common.less
thinkhazard/static/less/report.less

Adjust spacing between hazard sections

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Improvements on styling for zoom out and help blocks.
Please review.

Zoom out and zoom help

---

package.json
thinkhazard/static/js/report.js
thinkhazard/views/report.py

Fixes #229.
@elemoine it would be nice if you could have a review when you're back.

Show division outline on map

---

Makefile
production.ini

This PR suggests a few minor changes to the `Makefile` and `production.ini`. Please review.

Minor build-related changes

---

thinkhazard/static/js/report.js

Change base layer

---

thinkhazard/views/search.py

Use wildcard at the begining of search as well

---

thinkhazard/static/less/index.less
thinkhazard/templates/index.jinja2

Center the search field on the home page

---

thinkhazard/static/js/report.js
thinkhazard/views/report.py

This pull request fixes issues with countries like New Zealand or United States of America which extend from either side of the date line.

Fix issue w/ extent w/ countries wrapping dateline

---

thinkhazard/views/report.py

Fixes #278.
Database needs an update though because order is based on hazard type table order which is not what Stuart expects.

Sort hazards by hazard type instead of category type

---

thinkhazard/views/report.py

This improves query performances.
Please review.

Use WITH queries (CTE) to compute the countries extent

---

thinkhazard/views/report.py

Shifted longitude was relevant for countries like New Zealand but not for France or Spain.
With this pull request, we compare the shifted extent with the standard one and keep the one with the lower longitude range.

Use shifted extent only if relevant

---

thinkhazard/templates/search.jinja2

Change search place holder to sthing more explicit

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less

Fixes #301
We don't have much styling options with OL3 right now.
Here's how it looks. I hope this is fine.

Adding a map scale

---

thinkhazard/static/js/report.js

Changed opacities in map

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less

Changing color scheme

---

thinkhazard/templates/report.jinja2
thinkhazard/tests/test_report.py
thinkhazard/views/report.py

In overview, hazard should be sorted by level

---

thinkhazard/static/less/index.less

Center background image

---

thinkhazard/static/less/index.less

No shadow for navbar in home page

---

.travis.yml
README.rst
thinkhazard/scripts/initializedb.py
thinkhazard/static/less/icons.less
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/tests/__init__.py
thinkhazard/tests/test_report.py

Hazard type renamed

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

NPR becomes VLO - very low

---

development.ini
setup.py
tests.ini
thinkhazard/filters.py
thinkhazard/templates/report.jinja2

Adding markdown filter

---

thinkhazard/tests/__init__.py

See https://github.com/GFDRR/thinkhazard_common/pull/9
@fvanderbiest can you please review?

Fix association between admindiv and hazardcategory

---

requirements.txt
thinkhazard/tests/__init__.py

This pull request reverts a commit to fix the tests broken with latest version of thinkhazard_common and pin the version to an older "working" one.

Revert modifications on relation between hazardcategory and admindivs

---

thinkhazard/templates/search.jinja2

Change search placeholder

---

thinkhazard/templates/about.jinja2

Fix 'developed' misspelling

---

thinkhazard/tests/test_report.py
thinkhazard/views/report.py

Fixes #380.
https://github.com/GFDRR/thinkhazard/pull/381 needs to be merged first.

Fixing report json

---

thinkhazard/static/less/report.less
thinkhazard/templates/report.jinja2

Attribution for mapbox layer

---

thinkhazard/templates/about.jinja2

Updated Think Hazard! to ThinkHazard!, consistent with the main branding

Update to about.jinja2: Think Hazard! to ThinkHazard!

---

requirements.txt
thinkhazard/templates/report.jinja2
thinkhazard/tests/__init__.py
thinkhazard/tests/test_report.py
thinkhazard/views/report.py

With this pull request, we make usage of the new model which links hazard sets to admin divisions and hazard categories to display the sources which helped computing the resulting level.

data source

---

thinkhazard/static/less/bootstrap.less
thinkhazard/static/less/common.less
thinkhazard/static/less/index.less
thinkhazard/templates/about.jinja2
thinkhazard/templates/base.jinja2
thinkhazard/templates/common.jinja2
thinkhazard/templates/faq.jinja2

FAQ and about are now in modal windows

---

thinkhazard/models.py
thinkhazard/processing/harvesting.py
thinkhazard/scripts/harvest.py
thinkhazard/templates/report.jinja2
thinkhazard/tests/views/__init__.py
thinkhazard/tests/views/test_report.py
thinkhazard/views/report.py

With this pull request the data sources displayed in the report page are the link to "distribution_url" as set in the geonode metadata using the "owner__organization" as label.

Data sources

---

.gitignore

more concise .gitignore

---

README.rst

database name in readme matches default settings

---

README.rst
thinkhazard_processing.yaml

Remove french word "sig"

---

thinkhazard_processing.yaml

Related to https://github.com/GFDRR/thinkhazard/issues/403

PGA-g becomes PGA-g-dec

---

thinkhazard/tests/__init__.py

Removed unrequired code

---

thinkhazard/models.py
thinkhazard/processing/__init__.py
thinkhazard/processing/downloading.py

This invalidate raster data cache when data_lastupdated_date is newer than file in cache.
Also log traceback in downloading excepts.

Handle data_lastupdated_date when downloading

---

thinkhazard/models.py

Fixes #413.
~1800 ms -> ~20ms
It may have a good influence on a lot of other DB queries.
Please review.

Defer loading of geometry

---

thinkhazard/__init__.py
thinkhazard/templates/admin/hazardsets.jinja2
thinkhazard/views/admin.py

Page to list hazardsets

---

thinkhazard/templates/admin/hazardcategory.jinja2

I forgot this one.
Please review.

Remove square brackets for associations fields

---

Makefile
thinkhazard/scripts/initializedb.py

Completely reinit database with fresh datamodel, populated, and processed hazardsets.

Add reinit_all target to ease development

---

thinkhazard/templates/admin/common.jinja2

@pgiraud : can you review. After this you can add your links in admin navbar.

Fix admin navbar

---

thinkhazard/__init__.py
thinkhazard/models.py
thinkhazard/scripts/import.py
thinkhazard/static/less/admin.less
thinkhazard/templates/admin/climate_rec_form.jinja2
thinkhazard/templates/admin/climate_rec_index.jinja2
thinkhazard/templates/admin/common.jinja2
thinkhazard/tests/views/__init__.py
thinkhazard/tests/views/test_admin.py
thinkhazard/tests/views/test_search.py
thinkhazard/views/admin.py
thinkhazard/views/report.py

Add admin climate recommendations

---

thinkhazard/__init__.py
thinkhazard/templates/admin/admindiv_hazardsets.jinja2
thinkhazard/templates/admin/common.jinja2
thinkhazard/views/admin.py

admin menus for hazarsets related views

---

thinkhazard/views/report.py

Workaround for ST_Shift_Longitude behavior on date line.

Translate before applying ST_Shift_Longitude. Relate #391

---

README.rst
development.ini
production.ini
thinkhazard_processing.yaml

data_path set in .ini files

---

thinkhazard/models.py
thinkhazard/processing/harvesting.py
thinkhazard/tests/views/__init__.py
thinkhazard/tests/views/test_report.py
thinkhazard/tests/views/test_search.py
thinkhazard/views/report.py

This is a fix for #443 
In addition:
* the relation between `Region` and `AministrativeDivision` was simplified (no need for an association class)
* tests have been overhauled

Further resources & regions

---

thinkhazard/static/less/index.less

Search bar styling on index page

---

thinkhazard/views/report.py

utf8 encode feedback form params

---

thinkhazard/static/js/search.js
thinkhazard/views/search.py

Fix order of seach results on server side

---

thinkhazard/templates/about_body.jinja2

Adding link in about page

---

thinkhazard/processing/harvesting.py

Add forgotten commits in harvesting.

Fix harvesting commits

---

.gitignore
Makefile
package.json
thinkhazard/models.py
thinkhazard/processing/completing.py
thinkhazard/static/less/admin.less
thinkhazard/static/less/bootstrap.less
thinkhazard/templates/admin/admindiv_hazardsets.jinja2
thinkhazard/templates/admin/base.jinja2
thinkhazard/templates/admin/hazardsets.jinja2

Show the reason why hazardset is not complete

---

thinkhazard/templates/search.jinja2

Autofocus on search field

---

thinkhazard/views/report.py

Performance optimizations

---

thinkhazard/__init__.py
thinkhazard/static/js/report.js
thinkhazard/templates/data_source.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/templates/report_hazard_category.jinja2
thinkhazard/views/report.py

Adding view for data source modal content

---

requirements.txt
thinkhazard/__init__.py
thinkhazard/models.py
thinkhazard/static/js/report.js
thinkhazard/static/js/search.js
thinkhazard/templates/base.jinja2
thinkhazard/templates/pdf_cover.jinja2
thinkhazard/templates/pdf_report.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/templates/report_hazard_category.jinja2
thinkhazard/templates/search.jinja2
thinkhazard/tests/views/test_report.py
thinkhazard/views/report.py

Add slugified name in report urls

---

thinkhazard/static/less/report.less
thinkhazard/templates/pdf_report.jinja2

Changing PDF layout to better manage further resources / recommendations

---

thinkhazard/static/less/report.less

Replaced by SVG image
Fixes #511

Fix 404 error on missing logo image

---

thinkhazard/templates/admin/admindiv_hazardsets.jinja2

Changing col headers for admin levels

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less
thinkhazard/templates/report_hazard_category.jinja2

Map tooltip fix

---

Makefile
apache.conf

The main idea is to get the application running at the domain root. No extra "main/wsgi".
Please review.

apache conf enhancements

---

README.rst
thinkhazard/templates/analytics.jinja2
thinkhazard/templates/base.jinja2

Related to #513.
Please review.

Google analytics tracking

---

thinkhazard/scripts/publish.py

We need to clear wsgi variables after publication.

Restart apache after publication

---

thinkhazard/__init__.py
thinkhazard/templates/sitemap.jinja2
thinkhazard/tests/views/__init__.py
thinkhazard/tests/views/test_sitemap.py
thinkhazard/views/sitemap.py

Add sitemap view. Based on #537

---

Makefile
apache.conf

Prevent double slash issue in apache conf

---

thinkhazard/__init__.py
thinkhazard/scripts/publish.py
thinkhazard/templates/maintenance.jinja2
thinkhazard/tweens.py

Add maintenance page during publication

---

thinkhazard/processing/completing.py
thinkhazard/processing/processing.py

Relate #556
I've add a commit here to ensure that polygon and raster intersects. This should fix the memory error.

Verify that rasters properties match during complete.

---

thinkhazard/tweens.py

No cache on admin app

---

development.ini
thinkhazard/filters.py
thinkhazard/templates/about_body.jinja2

Works with "git describe" and should show tags when annotated tags are
available.

Show application version in about page

---

thinkhazard/__init__.py
thinkhazard/models.py
thinkhazard/templates/admin/climate_rec_index.jinja2
thinkhazard/templates/admin/technical_rec_index.jinja2
thinkhazard/views/admin.py

Add links to delete recommandations

---

thinkhazard/__init__.py
thinkhazard/views/index.py

Removing obsolete about & faq views

---

alembic/versions/c33a251714d6_change_drought_to_waterscarcity.py
thinkhazard/scripts/initializedb.py

Changing drought to water scarcity

---

README.rst

Add publish in readme

---

development.ini
production.ini
thinkhazard/__init__.py
thinkhazard/scripts/publish.py
thinkhazard/tests/views/test_report.py

Fix #530
Note that developpers should have to set local ``backup_path`` setting in ``adminapp``.

Archive database backups.

---

Makefile

Execute processes in verbose mode and remove duplicated target

---

README.rst

Replace make serve by serve_public and serve_admin in readme.

---

thinkhazard/views/report.py

Fix report_overview redirect when no data

---

thinkhazard/models.py
thinkhazard/processing/completing.py
thinkhazard/processing/decisiontree.py
thinkhazard/processing/harvesting.py

Amorvan clean output

---

thinkhazard/__init__.py
thinkhazard/templates/about.jinja2
thinkhazard/templates/base.jinja2
thinkhazard/templates/common.jinja2
thinkhazard/templates/faq.jinja2
thinkhazard/views/index.py

About and FAQ loaded remotely

---

thinkhazard/processing/harvesting.py

Do not use mask layers for hazarset owner

---

thinkhazard/templates/data_source.jinja2

Don't show mask return period in hazardset data source info

---

thinkhazard/templates/about_body.jinja2
thinkhazard/views/index.py

Show publication date in about page

---

alembic/versions/f58bd58cd6d4_Adding_detailed_column_to_tec_rec.py
thinkhazard/models.py
thinkhazard/templates/admin/technical_rec_form.jinja2
thinkhazard/templates/report_hazard_category.jinja2
thinkhazard/views/admin.py

Add detailed text for technical recommendation

---

thinkhazard_processing.yaml

New parameters for water scarcity (drought)

---

thinkhazard/views/admin.py

Sort hazardsets by id

---

alembic/versions/d49029073f8f_remove_column_output_coverage.py
thinkhazard/models.py
thinkhazard/processing/processing.py
thinkhazard/tests/processing/test_decision_tree.py

Remove column output.coverage

---

thinkhazard/tweens.py

Revert "Use app init time as last_modified header"

---

.gitignore
Makefile
development.ini
production.ini
thinkhazard/__init__.py
thinkhazard/settings.py

Get version at import time in python

---

README.rst
thinkhazard/processing/harvesting.py
thinkhazard/processing/processing.py
thinkhazard/tests/processing/test_process.py
thinkhazard_processing.yaml

And use threshold from mask unit for mask layer

Use return period from 2 to 5 for river flood mask layer

---

thinkhazard/templates/faq.jinja2

Added three FAQs at the bottom of list

Update FAQs - added three FAQs

---

thinkhazard/templates/faq.jinja2

This update does not include the correct links to 
thinkhazard-methodology-report_v1_8final.pdf
SanityCheck All hazard summary - 20160428.pdf
I will have to log on and update the file after those links are included

updated file to include new FAQs

---

thinkhazard/templates/about_body.jinja2
thinkhazard/templates/faq.jinja2

updated to include links to method report and sanity check report

---

thinkhazard/static/less/report.less

Use prefix for transform css

---

thinkhazard/templates/about_body.jinja2

Remove ICES from About page

---

thinkhazard/templates/about_body.jinja2

Add disclaimer and GAUL licence statement

---

.travis.yml

See https://www.mail-archive.com/ubuntu@lists.osgeo.org/msg00885.html

Fix Travis-CI Apt issue

---

thinkhazard/models.py
thinkhazard/templates/admin/hazardset.jinja2

Order the layers by level

---

.travis.yml
README.rst
thinkhazard/views/search.py

Allow search with unaccentuated characters

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less

Changing map colors

---

thinkhazard/templates/common.jinja2
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/views/index.py

Add feedback link to nav bar

---

thinkhazard/__init__.py
thinkhazard/static/less/common.less
thinkhazard/templates/about.jinja2
thinkhazard/templates/about_body.jinja2
thinkhazard/templates/base.jinja2
thinkhazard/templates/common.jinja2
thinkhazard/templates/disclaimer.jinja2
thinkhazard/templates/pdf_about.jinja2
thinkhazard/views/index.py

Put disclaimer as modal when landing on TH

---

thinkhazard/templates/base.jinja2
thinkhazard/templates/disclaimer.jinja2

Disclaimer

---

thinkhazard/templates/about_body.jinja2

include licence statement in v1 about page

---

alembic/versions/cc5db2014332_adding_ready_column_in_hazardtype.py
thinkhazard/models.py
thinkhazard/static/less/report.less
thinkhazard/views/index.py
thinkhazard/views/report.py

Manage which hazard types should be shown

---

thinkhazard/static/less/report.less

Add padding around icons in report page

---

alembic/versions/967e9eaaed70_add_extreme_heat_hazard_categories.py
thinkhazard_processing.yaml

Add processing parameters for extreme heat

---

development.ini
production.ini
setup.py
thinkhazard/filters.py
thinkhazard/static/less/common.less
thinkhazard/templates/disclaimer.jinja2

Avoid too long disclaimer

---

alembic/versions/804166ef07da_add_field_processing_layer_typename.py
thinkhazard/models.py
thinkhazard/processing/harvesting.py

Relate #689
In harvesting, import geonode ``typename`` into ``processing.layer.typename``.

Add field processing.layer.typename

---

API.md
alembic/versions/2a26a7ae26a0_change_distribution_url_into_detail_url.py
thinkhazard/models.py
thinkhazard/processing/harvesting.py
thinkhazard/static/less/admin.less
thinkhazard/templates/admin/hazardsets.jinja2
thinkhazard/templates/data_source.jinja2
thinkhazard/tests/processing/test_harvesting.py
thinkhazard/tests/views/__init__.py

Proposal for https://github.com/GFDRR/thinkhazard/issues/746
Waiting GFDRR's feedback before merging.

change distribution_url into detail_url

---

.travis.yml
Makefile
thinkhazard/__init__.py
thinkhazard/models.py
thinkhazard/static/js/report.js
thinkhazard/static/less/common.less
thinkhazard/static/less/report.less
thinkhazard/templates/report_hazard_category.jinja2

Map toggle view

---

thinkhazard/static/js/report.js

Thin black line could be confusing, what about a dashed one?

Change style for link on map

---

thinkhazard/processing/harvesting.py
thinkhazard/tests/thinkhazard_processing.yaml

This PR should fix unit tests of previous PR : 
https://github.com/GFDRR/thinkhazard/pull/769

Add new configuration keys for tests

---

thinkhazard_processing.yaml

Change wildfire parameters

---

Makefile
export.js
package.json
thinkhazard/__init__.py
thinkhazard/static/js/report.js
thinkhazard/templates/pdf_report.jinja2
thinkhazard/views/pdf.py

Fix map generation in PDF export

---

thinkhazard/__init__.py
thinkhazard/renderers.py
thinkhazard/templates/admin/admindiv_hazardsets.jinja2
thinkhazard/templates/admin/technical_rec_index.jinja2
thinkhazard/views/admin.py

CSV Export

---

thinkhazard/static/js/data_map.js
thinkhazard/static/js/index.js
thinkhazard/static/js/report.js
thinkhazard/static/less/bootstrap.less
thinkhazard/static/less/common.less
thinkhazard/static/less/index.less
thinkhazard/static/less/report.less
thinkhazard/templates/about_body.jinja2
thinkhazard/templates/common.jinja2
thinkhazard/templates/index.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/templates/report_hazard_category.jinja2

I've updated the home page mockup to fit entirely in a medium-sized mobile screen:

Responsive layout

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less
thinkhazard/templates/report_hazard_category.jinja2

Reduce further resources size & add toggler

---

thinkhazard/templates/common.jinja2

Avoid caching data map page in ≠ languages

---

thinkhazard/templates/faq.jinja2

Added text and 2 links to one FAQ: response link2='https://riskopendata.org/', link3='https://oasishub.co/'). Please merge to master if OK

Update faq.jinja2 - two new links

---

thinkhazard/static/js/report.js
thinkhazard/templates/report_hazard_category.jinja2

when one of its layer is protected. see #835

Fix data source display

---

thinkhazard/static/less/admin.less
thinkhazard/templates/admin/hazardsets.jinja2

Add Hazardsets column to check layer visibility

---

thinkhazard/static/js/report.js
thinkhazard/templates/report_hazard_category.jinja2

Add data owner to restricted text

---

thinkhazard/templates/about_body.jinja2

Replace SSBN logo with Fathom logo

Update About - replacement logo

---

thinkhazard/templates/faq.jinja2

New FAQ providing links to doc that contain list of external sites - #836

Update FAQ.jinja2 - General section (new FAQ)

---

thinkhazard/static/js/report.js
thinkhazard/static/less/report.less
thinkhazard/templates/report_hazard_category.jinja2

Avoid textoverflow in datasources

---

thinkhazard/processing/harvesting.py
thinkhazard/tests/processing/test_harvesting.py

Less fields are available when requesting layers collection in Geonode 2.8.
This make harvesting compatible by retrieving missing values from detailed layer response.

Make harvest compatible with Geonode 2.8

---

Dockerfile
Makefile
requirements.txt
thinkhazard/__init__.py
thinkhazard/static/js/report.js
thinkhazard/static/less/report_print.less
thinkhazard/templates/pdf_cover.jinja2
thinkhazard/templates/pdf_report.jinja2
thinkhazard/templates/report.jinja2
thinkhazard/tests/views/test_report.py
thinkhazard/views/pdf.py

~~Based on https://github.com/GFDRR/thinkhazard/pull/871~~
Synchronous request for now, may be enough with the performance gain of using pyppeteer. We'll see later if asynchronous generation needs to be restored.

Dockerize print using pyppeteer

---

README.md
requirements.txt
thinkhazard/analytics.py
thinkhazard/views/api.py
thinkhazard/views/report.py

PR sends hits to GA to track API usage (when production.ini is used).
A custom report is set up in GA interface to display this data.

[GSWBTH-10] Tracks API usage statistics

---

thinkhazard/processing/harvesting.py

Retry 3 times in case geonode return 503.

Better handle http errors in harvesting

---

thinkhazard/processing/completing.py
thinkhazard/processing/downloading.py
thinkhazard/processing/harvesting.py
thinkhazard/tests/processing/test_completing.py

Temporary overrides to publish landslide as soon as possible.

Temporary overrides

---

tests/processing/test_harvesting.py
tests/views/test_report.py
thinkhazard/processing/harvesting.py

Gswbth 17 remove datasets fixes

---

thinkhazard_processing.yaml

includes return period between 10 and 25 for CF HIG

[GSWBTH-18] adapts return period values for CF HIG

---

thinkhazard/renderers.py
thinkhazard/views/admin.py

[GSWBTH-45] Fixes csv export

---

thinkhazard/analytics.py
thinkhazard/views/api.py
thinkhazard/views/report.py

... and uses value from env vars / settings
Allows to set debug true manually for dev.

Gets rid of GA tracking ID in code

---

Dockerfile

Fix master
